/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ApiServer */

#ifndef _Included_ApiServer
#define _Included_ApiServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ApiServer
 * Method:    fib
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ApiServer_fib
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
