apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  strategy: {}
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: gcr.io/shailesh-shrestha-1/hello:latest
        name: hello
        imagePullPolicy: IfNotPresent
        # imagePullPolicy: Alwaysd
        resources: {}
        ports:
          - containerPort: 8000