/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hello */

#ifndef _Included_Hello
#define _Included_Hello
#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jstring JNICALL Java_Hello_sayHello(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
