apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: hello
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
        - ./*.java
        - ./*.cpp
        ignore:
        - ./*.so
        - ./*.o
        - ./*.h
        - ./*.jar
        - ./*.class
deploy:
  kubectl:
    manifests:
    - deploy.yaml